/* keys.h */

#ifndef KEYS_INCLUDED
#define KEYS_INCLUDED

#define ASCII_BACKSPACE      8
#define CR                  13
#define SPACE               32
#define DELETE             127
#define ESCAPE              27

#define NO                   0
#define YES                  1
#define CHOICE_ESCAPE       -1         


#define KEYS_HIGH_BIT      0x80

#define KEY_ENTER          128
#define KEY_ESCAPE         129
#define KEY_TAB            130
#define KEY_BACK_TAB       131
#define KEY_BACKSPACE      132
#define KEY_DELETE         133
#define KEY_DELETE_FAR     134
#define KEY_INSERT         135
#define KEY_UP             136
#define KEY_UP_FAR         137
#define KEY_DOWN           138
#define KEY_DOWN_FAR       139
#define KEY_LEFT           140
#define KEY_LEFT_FAR       141
#define KEY_RIGHT          142
#define KEY_RIGHT_FAR      143
#define KEY_HOME           144
#define KEY_HOME_FAR       145
#define KEY_END            146
#define KEY_END_FAR        147
#define KEY_PG_UP          148
#define KEY_PG_UP_FAR      149
#define KEY_PG_DN          150
#define KEY_PG_DN_FAR      151
#define KEY_PLUS           152
#define KEY_MINUS          153

#define KEY_F1             154
#define KEY_F2             155
#define KEY_F3             156
#define KEY_F4             157
#define KEY_F5             158
#define KEY_F6             159
#define KEY_F7             160
#define KEY_F8             161
#define KEY_F9             162
#define KEY_F10            163
#define KEY_F11            164
#define KEY_F12            165
#define KEY_F13            166
#define KEY_F14            167
#define KEY_F15            168
#define KEY_F16            169
#define KEY_F17            170
#define KEY_F18            171
#define KEY_F19            172
#define KEY_F20            173
#define KEY_F21            174
#define KEY_F22            175
#define KEY_F23            176
#define KEY_F24            177
#define KEY_F25            178
#define KEY_F26            179
#define KEY_F27            180
#define KEY_F28            181
#define KEY_F29            182
#define KEY_F30            183
#define KEY_F31            184
#define KEY_F32            185
#define KEY_F33            186
#define KEY_F34            187
#define KEY_F35            188
#define KEY_F36            189
#define KEY_F37            190
#define KEY_F38            191
#define KEY_F39            192
#define KEY_F40            193   /* !!! */

#define KEY_ALT_A          193   /* !!!!!!!!!!!!!!!!!!! */
#define KEY_ALT_B          194
#define KEY_ALT_C          195
#define KEY_ALT_D          196
#define KEY_ALT_E          197
#define KEY_ALT_F          198
#define KEY_ALT_G          199
#define KEY_ALT_H          200
#define KEY_ALT_I          201
#define KEY_ALT_J          202
#define KEY_ALT_K          203
#define KEY_ALT_L          204
#define KEY_ALT_M          205
#define KEY_ALT_N          206
#define KEY_ALT_O          207
#define KEY_ALT_P          208
#define KEY_ALT_Q          209
#define KEY_ALT_R          210
#define KEY_ALT_S          211
#define KEY_ALT_T          212
#define KEY_ALT_U          213
#define KEY_ALT_V          214
#define KEY_ALT_W          215
#define KEY_ALT_X          216
#define KEY_ALT_Y          217
#define KEY_ALT_Z          218

// add definitions for the Control keys.  RAC Oct 3, 1990.
// Control C is a special MSDOS key.
#define KEY_CTRL_A 1
#define KEY_CTRL_B 2
#define KEY_CTRL_C 3  // special break key
#define KEY_CTRL_D 4
#define KEY_CTRL_E 5
#define KEY_CTRL_F 6
#define KEY_CTRL_G 7
#define KEY_CTRL_H 8
#define KEY_CTRL_I 9
#define KEY_CTRL_J 10
#define KEY_CTRL_K 11
#define KEY_CTRL_L 12
#define KEY_CTRL_M 13
#define KEY_CTRL_N 14
#define KEY_CTRL_O 15
#define KEY_CTRL_P 16
#define KEY_CTRL_Q 17
#define KEY_CTRL_R 18
#define KEY_CTRL_S 19
#define KEY_CTRL_T 20
#define KEY_CTRL_U 21
#define KEY_CTRL_V 22
#define KEY_CTRL_W 23
#define KEY_CTRL_X 24
#define KEY_CTRL_Y 25
#define KEY_CTRL_Z 26

#define KEY_

#define KEY_EXCEPTION      255

#endif
